---
title: "EDS 240: Infographic"
---


```{r}
# Load packages
library(tidyverse)
library(ggalluvial)
```

```{r}
# Load data
jra_results <- read_csv(here::here('data', '19860105-20210731_race_result.csv')) |> 
    # Omit レース記号 columns
    select(-starts_with("レース記号"))
# teio filter
teio <- jra_results |> 
    filter(馬名　== "トウカイテイオー")
```

```{r}
jra_results_eng <- jra_results
# Translate df columns
colnames(jra_results_eng) <- c("race_pp_id", "race_id", "race_date", "race_meeting_number", "racecourse_code", "racecourse_name", "nth_raceday", "race_prereq", "race_number", "graded_race_nth_time", "race_name", "listed_graded_race", "steeplechase", "turf_dirt", "turf_dirt2_steeplechase", "left_right_straight", "inside_outside", "distance_m", "weather", "track_condition1", "track_condition2_steeplechase", "post_time", "final_position", "final_position_notes", "bracket_number", "horse_number", "horse_name", "horse_sex", "horse_age", "weight", "jockey_name", "finish_time", "margin", "corner1_position", "corner2_position", "corner3_position", "corner4_position", "final_600m_time", "win_odds_100Y", "popular_rank", "horse_weight", "horse_weight_diff", "east_west_foreign", "horse_trainer", "horse_owner", "prize_money_10kY")

```

```{r}
# Weather bar plot
jra_results_eng |> 
    group_by(weather) |> 
    summarise(count = n()) |> 
    ggplot(aes(x = count, y = fct_reorder(weather, count))) +
    labs(x = "Amount of Days", y = "Weather") +
    geom_bar(stat = "identity")
```

```{r}
# Horse age
jra_results_eng |> 
    ggplot(aes(x = horse_age)) +
    geom_histogram(bins = 15)
```

```{r}
# Total horse winnings
winnings_df <- jra_results_eng |> 
    group_by(horse_name) |> 
    summarise(total_winnings_10kY = sum(prize_money_10kY, na.rm = TRUE)) |> 
    arrange(desc(total_winnings_10kY))
```

```{r}
# Horse with 'most' wins
```

```{r}
# Horse weight throughout career & win rate?
```
```{r}
# Age effects on performance (top3 placement)
```

```{r}
# Horse gender & finish times?
```

```{r}
# Track type & finish times
```

```{r}
# 1993 Arima Kinen
arima_kinen_93 <- jra_results_eng |> 
    filter(race_name == "有馬記念" & year(race_date) == 1993)

ak_93_long <- arima_kinen_93 |> 
    pivot_longer(cols = c(corner1_position:corner4_position, final_position), names_to = "corner_number", names_pattern = "(.*)_position",
    values_to = "position")

ggplot(ak_93_long, aes(corner_number, factor(position), group = horse_name, color = horse_name)) +
    geom_line() +
    scale_y_discrete(limits = rev) +
    gghighlight::gghighlight(horse_name == "トウカイテイオー") +
    theme_minimal()

# ggplot(data = arima_kinen_93, aes(
#     axis1 = corner1_position, 
#     axis2 = corner2_position,
#     axis3 = corner3_position,
#     axis4 = corner4_position,
#     axis5 = final_position)) +
#     geom_alluvium(aes(fill = horse_name)) +
#     geom_stratum() 
```

```{r}
# All Arima Kinen, favorite to win & actual win
all_arima_kinen <- jra_results_eng |> 
    filter(race_name == "有馬記念") |> 
    mutate(favorite_won = case_when(
        popular_rank == 1 & final_position == 1 ~ 1,
        TRUE ~ 0
    )) |> 
    
    mutate(favorite_won_or_placed = case_when(
        popular_rank == 1 & final_position %in% c(1,2) ~ 1,
        TRUE ~ 0
    ))
```